
## 报错

### touch和torchvision版本冲突
```python
Traceback (most recent call last):
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/train_pt_model.py", line 39, in <module>
    results = model.train(
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/engine/model.py", line 813, in train
    self.trainer.train()
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/engine/trainer.py", line 206, in train
    self._do_train(world_size)
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/engine/trainer.py", line 324, in _do_train
    self._setup_train(world_size)
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/engine/trainer.py", line 263, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/utils/checks.py", line 662, in check_amp
    assert amp_allclose(YOLO("yolov8n.pt"), im)
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/utils/checks.py", line 649, in amp_allclose
    a = m(im, device=device, verbose=False)[0].boxes.data  # FP32 inference
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/engine/model.py", line 174, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/engine/model.py", line 565, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/dell/anaconda3/envs/yolo_rknn/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/engine/predictor.py", line 234, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/home/dell/pythonProject/rknn_yolo/ultralytics_yolov8/ultralytics/nn/autobackend.py", line 637, in warmup
    import torchvision  # noqa (import here so torchvision import time not recorded in postprocess time)
  File "/home/dell/anaconda3/envs/yolo_rknn/lib/python3.10/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/home/dell/anaconda3/envs/yolo_rknn/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/home/dell/anaconda3/envs/yolo_rknn/lib/python3.10/site-packages/torch/library.py", line 654, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/home/dell/anaconda3/envs/yolo_rknn/lib/python3.10/site-packages/torch/library.py", line 154, in _register_fake
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/home/dell/anaconda3/envs/yolo_rknn/lib/python3.10/site-packages/torch/_library/abstract_impl.py", line 31, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist
```
重新安装pytorch
```python
(yolo_rknn) dell@dell-Precision-3660:~/pythonProject/rknn_yolo/ultralytics_yolov8$ python -c "import torch; print(torch.__version__, torch.cuda.is_available())"                                                                                      
2.5.1 True  
```
安装torchvision的时候报错网络有错误
更换清华源下载，解决
```
pip install torchvision -i https://pypi.tuna.tsinghua.edu.cn/simple

```
